Fix to LibriTTS formatter
coqui-ai/TTS pull request #1386
Opened 2022-03-13 20:02 UTC by stanleyshly

Sorry for the small PR, just discovered a bug with the LibriTTS formatter, and I thought I would open up a pull request to solve the issued I opened: #1380.

2022-03-13 20:02 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/coqui-ai/TTS?pullRequest=1386) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/coqui-ai/TTS?pullRequest=1386) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/coqui-ai/TTS?pullRequest=1386) it.</sub>

2022-03-14 12:52 UTC, erogol requested changes

2022-03-14 17:37 UTC, stanleyshly commented on TTS/tts/datasets/formatters.py
> +        assert os.path.exists(item["audio_file"]), f" [!] wav files don't exist - {item[1]}"
Changes made

2022-03-16 11:02 UTC, erogol commented
I close this as there are errors. Thanks for the try but I fix it myself.

2022-03-16 11:02 UTC, closed without merging