Multilingual tokenizer
coqui-ai/TTS pull request #2229
Opened 2022-12-20 17:16 UTC by WeberJulian

Add ability to specify language and tokenizer for each dataset.

```python
from TTS.tts.utils.text.phonemizers.multi_phonemizer import MultiPhonemizer
texts = {
    "tr": "Merhaba, bu Türkçe bit örnek!",
    "en-us": "Hello, this is English example!",
    "de": "Hallo, das ist ein Deutches Beipiel!",
    "zh-cn": "这是中国的例子",
}
phonemes = {}
ph = MultiPhonemizer({"tr": "espeak", "en-us": "", "de": "gruut", "zh-cn": ""})
for lang, text in texts.items():
    phoneme = ph.phonemize(text, lang)
    phonemes[lang] = phoneme
print(phonemes)
```

You set `language` and `phonemizer` for each dataset in the config/recipe. If `phonemizer` is not specified, it's using the default phonemizer for that language.

2022-12-20 17:18 UTC, WeberJulian commented
I'll add tests when that approach/design is validated.

2022-12-20 18:25 UTC, Edresson approved these changes
Great PR :)

2022-12-20 20:39 UTC, erogol requested changes
Just need testing for multi-lang phonemizer

2022-12-22 14:30 UTC, erogol approved these changes

2022-12-22 14:30 UTC, erogol commented
I approved it but it is still Draft. Is there something more to come?

2022-12-22 14:34 UTC, WeberJulian commented
> I approved it but it is still Draft. Is there something more to come?

I just wanted to see if the test were passing.
Also wondering about the text_cleaners, should we allow the by the same way we allow setting phonemizer for each dataset?
Or do we consider that phonemizers should also do the work that `multilingual_cleaner` doesn't (like espeak does)

2022-12-26 10:33 UTC, mraj96 commented
This PR not working for me. A few steps after training were stuck (freeze)

2022-12-26 10:42 UTC, erogol commented
I think we should be able to set different cleaners per dataset.

2022-12-26 11:41 UTC, mraj96 commented
> I think we should be able to set different cleaners per dataset.

any reason why we should set different cleaners per dataset? 

How to implement it? needed initial guidance.

if I add a set of different cleaners per dataset in cleaners.py, and  **BaseDatasetConfig** I am setting up text_cleaner, 

a similar way of, MultiPhonemizer to implement MultiCleaners in tokenizer.py init_from_config.

2022-12-26 14:47 UTC, Edresson commented
> rent cleaners per dataset in cleaners.py, and BaseDatasetConfig includes text_cleaners and a similar way of implementing MultiCleaners in tokenizer.py init_from_config.
> 
> better I will move to issues for this conversation

It would be nice, But I don't think that @MuruganR96 issue is related to it.  [multilingual_cleaners](https://github.com/coqui-ai/TTS/blob/f814d523945fc43071d037a1fb9edcdad99949b2/TTS/tts/utils/text/cleaners.py#L139) is simple and should be compatible with all languages.

2022-12-26 15:21 UTC, MuruganR96 commented
Thank you @WeberJulian  @erogol  @Edresson 

PR is working fine. espeak is not having support for the Telugu language. espeak-ng created this problem. so I uninstalled espeak-ng. now I am able to train Multilingual-MultiSpeaker TTS in English & Tamil.

2023-01-02 09:03 UTC, merged

2023-06-18 07:54 UTC, Msahiitrpr commented
@erogol @Edresson 
espeak-ng is not suporting training language , is there any specific reason ??. how to solve that