Api model path
coqui-ai/TTS pull request #2303
Opened 2023-01-23 12:50 UTC by erogol

Allow loading models from model files

2023-01-24 13:16 UTC, WeberJulian requested changes
Looks good, but it doesn't support specifying a vocoder unlike the `load_model_by_name`.

2023-01-24 21:36 UTC, erogol commented
right. I didnt need it when I needed it but for making the PR right makes sense

2023-01-30 12:37 UTC, erogol commented
@WeberJulian I also add voice cloning.

2023-01-31 09:45 UTC, WeberJulian approved these changes

2023-02-06 10:21 UTC, merged