…
coqui-ai/TTS pull request #2587
Opened 2023-05-04 18:20 UTC by wonkothesanest

It looks like the Neon model is special in that t does not have a speaker_name and it wants to get the only item available. This was blocking a valid model with one speaker and a d_vector_file from being executed to get the embedding.

It looks like the Neon model is special in that t does not have a speaker_name and it wants to get the only item available.
This was blocking a valid model with one speaker and a d_vector_file from being executed to get the embedding.

Leaving the check to be second still works fine for the case that there is only one model and no speaker name.

This is in reference to bug 2320
https://github.com/coqui-ai/TTS/issues/2320

(updated from  trying to get my author right)

2023-05-04 19:15 UTC, wonkothesanest commented
Can someone please guide me to some documentation on how to get the tests to pass? I believe there is not a correct token setup for Coqui TTS.
"No API token found for 🐸Coqui Studio voices - https://coqui.ai/ \n"

2023-05-08 08:59 UTC, erogol requested changes

2023-05-08 08:59 UTC, erogol commented on TTS/utils/synthesizer.py
> +            elif len(sef.tts_model.speaker_manager.name_to_id) == 1:
sef -> self.

2023-05-13 18:00 UTC, wonkothesanest commented on TTS/utils/synthesizer.py
> +            elif len(sef.tts_model.speaker_manager.name_to_id) == 1:
wow that's embarrassing 😬

2023-05-15 03:42 UTC, wonkothesanest commented
I have 5 failing tests all of which seem to have to do with not having a Coqui Studio Token.  Can someone please help me understand how I might be able to fix this issue?  I don't see where I could set the environment to add this token.

Relevant error message:
```
> Generator Model: multiband_melgan_generator
 > Discriminator Model: melgan_multiscale_discriminator
 > Text: This is an example.
 > Text splitted to sentences.
['This is an example.']
 > Processing time: 0.34621286392211914
 > Real-time factor: 0.15287555369838846
 > Saving output to /home/runner/work/TTS/TTS/tests/outputs/output.wav
 > Using 🐸Coqui Studio model:  coqui_studio/en/Torcull Diarmuid/coqui_studio
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.16/x64/bin/tts", line 8, in <module>
    sys.exit(main())
  File "/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/TTS/bin/synthesize.py", line 330, in main
    api = TTS(model_name=args.model_name)
  File "/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/TTS/api.py", line 285, in __init__
    self.load_tts_model_by_name(model_name, gpu)
  File "/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/TTS/api.py", line 375, in load_tts_model_by_name
    self.csapi = CS_API()
  File "/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/TTS/api.py", line 67, in __init__
    self._check_token()
  File "/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/TTS/api.py", line 94, in _check_token
    "No API token found for 🐸Coqui Studio voices - https://coqui.ai/ \n"
ValueError: No API token found for 🐸Coqui Studio voices - https://coqui.ai/ 
Visit 🔗https://app.coqui.ai/account to get one.
Set it as an environment variable `export COQUI_STUDIO_TOKEN=<token>`

FAIL
```

2023-06-14 02:20 UTC, wonkothesanest commented
@erogol Anything else I need to do here for this PR?

2023-06-21 13:37 UTC, erogol commented
@wonkothesanest thx for the PR. I'll review it as soon as I can

2023-07-04 07:09 UTC, wonkothesanest commented
@erogol 
Anything else needed from me on this pr?

2023-10-16 09:55 UTC, merged